server:
  port: 8082
  server:
    context-path: /bookstore


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root